### ISSUE TITLE
Mac OS Catalina Unicode Error

### ISSUE THREAD

**Issue by lxmmxl56** [AcidWeb/CurseBreaker#142]
The latest version (3.9.4) gives the following error on run:

```
Traceback (most recent call last):
\u256d\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256e
\u2502 File "CurseBreaker.py", line 738, in <module>                                                    \u2502
\u2502 File "CurseBreaker.py", line 57, in start                                                        \u2502
\u2502 File "CurseBreaker.py", line 253, in print_header                                                \u2502
\u2502 File "rich/console.py", line 902, in print                                                       \u2502
\u2502 File "rich/console.py", line 447, in __exit__                                                    \u2502
\u2502 File "rich/console.py", line 425, in _exit_buffer                                                \u2502
\u2502 File "rich/console.py", line 1022, in _check_buffer                                              \u2502
\u2570\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256f
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-43: ordinal not in range(128
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
[24777] Failed to execute script CurseBreaker
```

I have tried `export PYTHONIOENCODING=utf-8` but I think I must not be hitting right env.

Any thoughts?

**Comment by lxmmxl56** [comment]
Thanks for the hint; my `locale` output was all set to `C`.  Adding `export LANG="en_US.utf-8"` to my `~/.bash_profile` fixed the issue.
