### ISSUE TITLE
UnicodeEncodeError while backing up WTF directory

### ISSUE THREAD

**Issue by tkmehta** [AcidWeb/CurseBreaker#150]
```
Backing up WTF directory: 
1037/1369 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━ |
UnicodeEncodeError: 'ascii' codec can't encode character '\udcee' in position 43: o
range(128)

During handling of the above exception, another exception occurred:


UnicodeEncodeError: 'utf-8' codec can't encode character '\udcee' in position 43: s
allowed
```

I am running Linux.

**Comment by AcidWeb** [comment]
Show me output of `locale` command from environment you using to start CB.

**Comment by tkmehta** [comment]
````
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
````

**Comment by AcidWeb** [comment]
You got that error only during backup?

**Comment by tkmehta** [comment]
That's correct

**Comment by AcidWeb** [comment]
`wago_update` command is not returning any error?

**Comment by tkmehta** [comment]
No, it's not.

If it's helpful, I had an issue with WeakAurasCompanion not finding the addons directory due to a capitalized letter in the path. Not sure if this is related.

**Comment by AcidWeb** [comment]
It looks like there is a file in your WTF directory that have strange content.

**Comment by tkmehta** [comment]
Any way to figure out which file?

**Comment by tkmehta** [comment]
Okay, I found removed a couple of folders named after characters with special characters. Hopefully, this will fix the issue. However, I'm not sure how to force cursebreaker to backup WTF directory. Is there way to induce a backup manually?

**Comment by AcidWeb** [comment]
Delete today backup.

Also that characters should not cause the problem.

**Comment by tkmehta** [comment]
Thanks! The backup is working now. That seems to have been the issue.

**Comment by AcidWeb** [comment]
What kind of characters were used?

**Comment by tkmehta** [comment]
\Xee

**Comment by tkmehta** [comment]
Oh, and \Xe5

**Comment by AcidWeb** [comment]
I need to check it out as this should not be a problem.

**Comment by AcidWeb** [comment]
I can't replicate this issue. I can use both \Xee and \Xe5 without any issue.
I still think that was caused by contents of files that where in deleted directories.

**Comment by tkmehta** [comment]
I think you might be right. I created empty directories with those characters as before and had no issues. Weird. Thanks for looking into this.

**Comment by AcidWeb** [comment]
Do you have any other backup of these directories? I really would like to check the content.

**Comment by tkmehta** [comment]
[WTF-unicode-errors.zip](https://github.com/AcidWeb/CurseBreaker/files/5219960/WTF-unicode-errors.zip)
Here you go

**Comment by AcidWeb** [comment]
Thanks. I will take a look.

**Comment by AcidWeb** [comment]
Still can't replicate this issue. Archive is clear as a whistle.

**Comment by AcidWeb** [comment]
Can't replicate it locally. Any chance you could run this application from sources and provide full error stack? (I really need to add debug to binary release)

**Comment by tkmehta** [comment]
Yeah, I'll do it later today. Is there anything specific I need to do when building from source?

**Comment by AcidWeb** [comment]
Nothing to build there. You can directly run it with python if you have dependencies installed. Set `CURSEBREAKER_PATH` env variable with path to WoW client.

**Comment by tkmehta** [comment]
Here's the full error stack: 

```
Traceback (most recent call last):

╭─────────────────────────────────────────────────────────────────────────────────╮
│ File "/usr/lib/python3.8/zipfile.py", line 457, in _encodeFilenameFlags         │
│     454                                                                         │
│     455     def _encodeFilenameFlags(self):                                     │
│     456         try:                                                            │
│  ❱  457             return self.filename.encode('ascii'), self.flag_bits        │
│     458         except UnicodeEncodeError:                                      │
│     459             return self.filename.encode('utf-8'), self.flag_bits | 0x800│
│     460                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────╯
UnicodeEncodeError: 'ascii' codec can't encode character '\udce5' in position 35: o
range(128)

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
╭─────────────────────────────────────────────────────────────────────────────────╮
│ File "CurseBreaker.py", line 150, in start                                      │
│ File "/home/tanay/Games/world-of-warcraft-classic/drive_c/Program Files         │
│(x86)/World of Warcraft/_classic_/CurseBreaker.temp/CurseBreaker/CB/Core.py",    │
│line 406, in backup_wtf                                                          │
│    403                 for root, _, files in os.walk('WTF/', topdown=True, follo│
│    404                     files = [f for f in files if not f[0] == '.']        │
│    405                     for f in files:                                      │
│  ❱ 406                         zipf.write(Path(root, f))                        │
│    407                         progress.update(task, advance=1, refresh=True)   │
│    408         zipf.close()                                                     │
│    409                                                                          │
│ File "/usr/lib/python3.8/zipfile.py", line 1775, in write                       │
│    1772                 self.fp.write(zinfo.FileHeader(False))                  │
│    1773                 self.start_dir = self.fp.tell()                         │
│    1774         else:                                                           │
│  ❱ 1775             with open(filename, "rb") as src, self.open(zinfo, 'w') as d│
│    1776                 shutil.copyfileobj(src, dest, 1024*8)                   │
│    1777                                                                         │
│    1778     def writestr(self, zinfo_or_arcname, data,                          │
│ File "/usr/lib/python3.8/zipfile.py", line 1517, in open                        │
│    1514             zinfo = self.getinfo(name)                                  │
│    1515                                                                         │
│    1516         if mode == 'w':                                                 │
│  ❱ 1517             return self._open_to_write(zinfo, force_zip64=force_zip64)  │
│    1518                                                                         │
│    1519         if self._writing:                                               │
│    1520             raise ValueError("Can't read from the ZIP file while there "│
│ File "/usr/lib/python3.8/zipfile.py", line 1614, in _open_to_write              │
│    1611         self._writecheck(zinfo)                                         │
│    1612         self._didModify = True                                          │
│    1613                                                                         │
│  ❱ 1614         self.fp.write(zinfo.FileHeader(zip64))                          │
│    1615                                                                         │
│    1616         self._writing = True                                            │
│    1617         return _ZipWriteFile(self, zinfo, zip64)                        │
│ File "/usr/lib/python3.8/zipfile.py", line 447, in FileHeader                   │
│     444                                                                         │
│     445         self.extract_version = max(min_version, self.extract_version)   │
│     446         self.create_version = max(min_version, self.create_version)     │
│  ❱  447         filename, flag_bits = self._encodeFilenameFlags()               │
│     448         header = struct.pack(structFileHeader, stringFileHeader,        │
│     449                              self.extract_version, self.reserved, flag_b│
│     450                              self.compress_type, dostime, dosdate, CRC, │
│ File "/usr/lib/python3.8/zipfile.py", line 459, in _encodeFilenameFlags         │
│     456         try:                                                            │
│     457             return self.filename.encode('ascii'), self.flag_bits        │
│     458         except UnicodeEncodeError:                                      │
│  ❱  459             return self.filename.encode('utf-8'), self.flag_bits | 0x800│
│     460                                                                         │
│     461     def _decodeExtra(self):                                             │
│     462         # Try to decode the extra field.                                │
╰─────────────────────────────────────────────────────────────────────────────────╯
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce5' in position 35: s
allowed
```

**Comment by tkmehta** [comment]
I also found [this discussion](https://bugs.python.org/issue13717), which seems relevant.

**Comment by AcidWeb** [comment]
Well if walk is returning lone surrogates then there is definitely something wrong with some file/directory names in yours WTF directory.

In `CB/Core.py` after line 405 add `print(f)`. Lets see what it will print.

**Comment by tkmehta** [comment]
https://pastebin.com/jGAK8b5T

**Comment by AcidWeb** [comment]
Show me output of `ls -l` from `Scňtterbrain` and `Scatterbraţn` directories.

**Comment by tkmehta** [comment]
`WTF\Account`:
```
total 8
drwxr-xr-x 9 tanay tanay 4096 Mar 28 12:42 961253#1
drwxr-xr-x 2 tanay tanay 4096 Mar 28 12:42 SavedVariables
```
`Scatterbraîn`:
```
total 32
-rw-r--r-- 1 tanay tanay 2872 Sep 14 12:02 AddOns.txt
-rw-r--r-- 1 tanay tanay  120 Sep 14 12:02 cache.md5
-rw-r--r-- 1 tanay tanay 4305 Sep 14 12:02 chat-cache.txt
-rw-r--r-- 1 tanay tanay  464 Sep 14 12:02 config-cache.old
-rw-r--r-- 1 tanay tanay  461 Sep 14 12:02 config-cache.wtf
-rw-r--r-- 1 tanay tanay  241 Sep 14 12:02 layout-local.txt
drwxr-xr-x 2 tanay tanay 4096 Sep 14 12:02 SavedVariables
```
`Scåtterbrain/`
```
total 32
-rw-r--r-- 1 tanay tanay 2872 Sep 14 12:02 AddOns.txt
-rw-r--r-- 1 tanay tanay  120 Sep 14 12:02 cache.md5
-rw-r--r-- 1 tanay tanay 4270 Sep 14 12:02 chat-cache.txt
-rw-r--r-- 1 tanay tanay  404 Sep 14 12:02 config-cache.old
-rw-r--r-- 1 tanay tanay  401 Sep 14 12:02 config-cache.wtf
-rw-r--r-- 1 tanay tanay  168 Sep 14 12:02 layout-local.txt
drwxr-xr-x 2 tanay tanay 4096 Sep 14 12:02 SavedVariables
```

**Comment by AcidWeb** [comment]
If you remove `Scatterbraîn` and `Scåtterbrain` directories it start to work yes? Try to remove `cache.md5`file from both of them.

**Comment by tkmehta** [comment]
Yes, if those directories are removed then it works. I removed `cache.md5` in both and it still gives the same error.

**Comment by tkmehta** [comment]
I removed all files from those directories. There was no error. Then, I put an empty text file in each directory with no other files present. This yielded in the error again. So, it looks like the issue with the directory names.

**Comment by AcidWeb** [comment]
Thank you for extensive test. Sadly even with that knowledge I can't replicate this issue in any of my Linux environments.
