### ISSUE TITLE
unable to run remotely using powershell in headless mode

### ISSUE THREAD

**Issue by optimizedconfusion** [AcidWeb/CurseBreaker#242]
I was hoping to use the **headless** option to run updates on other computers using powershell but I get the following error:

```
[192.168.4.99]: PS C:\World of Warcraft\_retail_> .\CurseBreaker.exe headless
.\CurseBreaker.exe : Traceback (most recent call last):
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

  File "CurseBreaker.py", line 881, in <module>
  File "CurseBreaker.py", line 49, in __init__
  File "prompt_toolkit\shortcuts\prompt.py", line 466, in __init__
  File "prompt_toolkit\shortcuts\prompt.py", line 717, in _create_application
  File "prompt_toolkit\application\application.py", line 271, in __init__
  File "prompt_toolkit\application\current.py", line 70, in output
  File "prompt_toolkit\output\defaults.py", line 70, in create_output
  File "prompt_toolkit\output\win32.py", line 107, in __init__
  File "prompt_toolkit\output\win32.py", line 211, in get_win32_screen_buffer_info
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
[5760] Failed to execute script CurseBreaker
```

Is updating using the headless option currently supported when running commands remotely through powershell?

Thanks for all of your work on this app!

**Comment by AcidWeb** [comment]
I highly doubt that PS is supported in any form.
